### PR TITLE
updated for coreldraw 2020

### PR DESCRIPTION
**Pull request by NelisW**
original code gave error message: changed init(string template, bool useTemplate, string title) to put selectall inside else clause

### CODE REVIEW

**Comment by janbender** [comment]
I didn't have time yet to test the changes on my system but I just took a short look on them. Maybe it would be good to add a new file  Latex4CorelDraw2020.csproj instead of changing the current  Latex4CorelDraw.csproj. In this way it would work on both versions.

**Comment by paolo-fix** [comment]
Any idea why I obtain that the docker shows an empty interface?
I'm using Corel Draw 2019...
Many thanks
Paolo
Cattura

**Comment by janbender** [comment]
If the docker is empty, CorelDraw did not load the plugin due to some reason. Did you use the precompiled binaries? They were compiled for CorelDraw x8. So for your version you have to recompile the plugin. Maybe also take a look at this comment:

https://github.com/InteractiveComputerGraphics/Latex4CorelDRAW/issues/4#issuecomment-612365085

**Comment by paolo-fix** [comment]
Thank you for the answer Jan.
I'm not familiar with rebuilding, compiling with Visual Studio.
On the website of Microsoft I've Seen there is a free version of Visual
studio. do you think it is going to be sufficient to rebuild your app?
Paolo

Il ven 6 nov 2020, 12:06 Jan Bender <notifications@github.com> ha scritto:

**Comment by NelisW** [comment]
Hi Paolo-fix

Firstly, a big thanks to Jan, this is a really nice tool!

Perhaps this can help. I built this with VS2019 for Coreldraw 2020
My fork of Jan's git repo is at https://github.com/NelisW/Latex4CorelDRAW

On my PC the addon files are located here:
C:\Program Files\Corel\CorelDRAW Graphics Suite
2020\Programs64\Addons\Latex4CorelDraw folder.
I made you copies of all the files in this folder on myPC.

I cannot add the files as an attachment to the email, the security policy
does not allow.
We can try two ways to get the compiled binary files to you - one of them
should work.

1)
Download all the files from here into the above (or similar for your PC)
folder.
https://github.com/NelisW/Latex4CorelDRAW/tree/master/Latex4CorelDrawFolder.

2)
The files are here https://www.dropbox.com/t/0MvPY2RjH2YdqysQ - the link
only lasts a few days, so please download soon.
Copy the files in the transfer zip to the above folder.

I hope this helps. let me know at neliswillers@gmail.com.

regards

Nelis

**Comment by janbender** [comment]
Hi Paolo, I think the fork of NelisW could help you. Unfortunately, I did not find the time yet to merge it but I think it would make sense to add multiple project files for different versions of CorelDraw. Since I have an older version, I cannot provide the binaries.

**Comment by livesdlc** [comment]
It does not work on any version. Tested on Corel X7, X8 and 2020, 64 bit and Windows 10. I followed exactly the steps. Nothing works. Docker is empty. Me fez perder um puta tempo.

**Comment by NelisW** [comment]
Hi

I checked the files just now, installing to a new PC. It works.
I rewrote the readme to be more explicit for my procedure [we are not
following the original Jan Bender procedure any more].
please try the new writeup (attached hereto and also pushed to github).

all of the best

n

**Comment by paolo-fix** [comment]
Dear Nelis,
Let me first thank you sincerely.
However I'm afraid we have a small problem... Do you think your late
solution could work also on my version 2019? I expect not, given the usual
strict link of the compilation each different version.
But maybe your new approach is more general.
Best regards,
Paolo


Il giorno dom 28 mar 2021 alle ore 13:15 Nelis Willers <
***@***.***> ha scritto:

**Comment by paolo-fix** [comment]
I confirm that unfortunately on my (win10 + CorelDraw 2019) system the
latex docker appears on the menu, but it remains all grey.
[image: CorelDraw2019_Latex.PNG]

Il giorno dom 28 mar 2021 alle ore 23:59 Paolo Falbo ***@***.***>
ha scritto:

**Comment by NelisW** [comment]
Hi Paolo

Try this version, I am not sure it will work though.

I don't have a Windows c++ compiler currently, we are currently  using the
Linux compilers on WSL2. Very nice to boot in Windows but have command line
access to linux. The next version of WSL later this year will have full
Linux gui and gpu support.

The best would be for you to install visual studio 2019 CE and build the
Release version dll file for your coreldraw version,  follow my work flow,
but change CD version as per your required need. Then, once the dll is
built, copy it over my version. Only the one Latex4CorelDraw.dll file need
to rebuilt, the other files should work fine.

Sorry, I would not be able to compile new binaries: I have no current need
to load visual studio on Windows.

Jan Bender did a very good job with the addon, so if you are able to
compile the dll, all should be fine.

Good luck!

**Comment by alecsilveira** [comment]
Thank you all. I have it working on CorelDraw 2021.

Regards,
Alex

**Comment by paolo-fix** [comment]
Dear Nelis,
After about one year of your unvaluable and successful help, I'm afraid I need it again... (I had to reinstall my system) 
Using your files and following your instructions:
1. I modified Latex4CorelDraw.csproj (to replace original path C:\Program Files\Corel\CorelDRAW Graphics Suite 2020\ to C:\Program Files\Corel\CorelDRAW Graphics Suite 2019\) and 
2. compiled Latex4CorelDraw project with VS2017 CE (with no errors).
3. 9 files are created in the C:\Program Files\Corel\CorelDRAW Graphics Suite 2019\Programs64\Addons\Latex4CorelDraw, including Latex4CorelDraw.dll.
 
However, it seems results are only partly successful. 
On the one side, the Latex Docker pops-up and I succeed to regularly "preview" math equations.
image

Yet, after a few seconds that I click on OK to confirm, an error message appears, saying that  
System.Runtime.InteropServices.COMException (0x80004005): Errore HRESULT E_FAIL returned by a call to a COM component (see later for additional messages)
and the equation does not paste into CorelDraw (below I pasted a translation in English...)
image

I can replicate the error. I also have the details of the problem detected using the Debug of VS2017. 
image
image

An (almost random) detail that I checked is that the imagefile:
C:\Users\Paolo\AppData\Roaming\Latex4CorelDraw\teximport.pdf
is not actually created. This is what I see in that folder during the debugging.
image

Useless to say, If you could solve of this, it would be a huge help! I really have no clue how to solve this... (I can send you my email address and provide the detalis of debugging, if you like).

best, Paolo

****
   in Corel.Interop.VGCore.LayerClass.ImportEx(String FileName, cdrFilter Filter, StructImportOptions Options)
   in Latex4CorelDraw.LatexDialog.generateEquation(Boolean createShape)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by janbender** [comment]
If the pdf file is not generated, maybe it is a problem with the converter. Could you try to run the PDF conversion command on command line?

**Comment by paolo-fix** [comment]
> If the pdf file is not generated, maybe it is a problem with the converter. Could you try to run the PDF conversion command on command line?

Jan, I tried with a simple example. Apparently pdflatex correctly works...

image

and the pdf file was generated...
image

Is this the test you meant?

**Comment by janbender** [comment]
I meant something similar. In the plugin I first generate a PS file and then convert it in line:

https://github.com/InteractiveComputerGraphics/Latex4CorelDRAW/blob/e17b3658763ef9d1e668ca00c4ecd047a32193c2/AddinUtilities.cs#L351

The command is: 

 startProcess("cmd.exe", "/c \"" + mgr.SettingsData.miktexPath + "\\ps2pdf.exe\" -dNoOutputFonts teximport.ps teximport.pdf", true, false, out output);

Or on command line: 

<miktexPath>\ps2pdf.exe -dNoOutputFonts teximport.ps teximport.pdf

Can you try if this works?

**Comment by paolo-fix** [comment]
> I meant something similar. In the plugin I first generate a PS file and then convert it in line:
> 
> https://github.com/InteractiveComputerGraphics/Latex4CorelDRAW/blob/e17b3658763ef9d1e668ca00c4ecd047a32193c2/AddinUtilities.cs#L351
> 
> The command is:
> 
> startProcess("cmd.exe", "/c "" + mgr.SettingsData.miktexPath + "\ps2pdf.exe" -dNoOutputFonts teximport.ps teximport.pdf", true, false, out output);
> 
> Or on command line:
> 
> \ps2pdf.exe -dNoOutputFonts teximport.ps teximport.pdf
> 
> Can you try if this works?

Dear Jan, bingo! 👍 
I tried your command from the command line and noticed that the ps2pdf was not recognized! Indeed the System Path (environmental variables of Windows) was including a wrong path to MikTek, that I immediately updated.
After updateing the path, your Latex Addon in CorelDraw immediately generated the desired Latex expression!
Brilliant solution.
Of course, thanks a lot!

image

**Pull request closed without merging**
